Share chat public
potpie-ai/potpie pull request #137
Opened 2024-10-28 15:57 UTC by GodReaper

2024-10-29 15:52 UTC, GodReaper commented
<img width="504" alt="Screenshot 2024-10-29 at 8 58 59 PM" src="https://github.com/user-attachments/assets/db4d2da5-23bf-4eca-87b0-f3b7eba4a7fa">
<img width="504" alt="Screenshot 2024-10-29 at 8 59 03 PM" src="https://github.com/user-attachments/assets/eed2e6fa-367e-426b-8c5b-c102c3feef51">

2024-10-29 16:53 UTC, dhirenmathur requested changes

2024-10-29 16:53 UTC, dhirenmathur commented on app/alembic/versions/20241026151704_e824fba2b86a_new_migration.py
> +Revision ID: 20241026151704_e824fba2b86a
is this file still needed? just undo this migration and generate a new one instead of fixing this in the next one

2024-10-30 13:54 UTC, dhirenmathur requested changes

2024-10-30 13:54 UTC, dhirenmathur commented on app/modules/conversations/conversations_router.py
> +):
Where is the authorisation? 
Add auth and make sure that the get emails endpoint returns 401 when a user who is not the conversation owner tries to request them

2024-11-01 07:02 UTC, merged